version: '3.3'
services:

  mysql:
      image: mysql:8.0
      # 設定 mysql 使用原生認證的密碼 hash
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports: 
          - 127.0.0.1:3306:3306
      env_file:
        - line_notify/docker/.env
      volumes:
          - /data/langisland/mysql:/var/lib/mysql
      networks:
          - lang

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
      ports:
          - 127:0:0:1311:80
      depends_on:
        - mysql
      networks:
          - lang

  linenotify:
    image: service-line-notify
    volumes:
      - ./line_notify/src:/home/app/workdir/src
      - ./line_notify/main.py:/home/app/workdir/main.py
    env_file:
      - line_notify/docker/.env
    ports:
      - 5001:5001
    depends_on:
      - mysql
    networks:
      - lang
    
     
networks:
  lang:
    external: true